# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-06 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='old dojo', max_length=45),
            preserve_default=False,
        ),
    ]
